# Generated by Django 2.0.1 on 2018-04-30 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0006_auto_20180430_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate', models.CharField(max_length=50)),
                ('count', models.CharField(max_length=100)),
                ('price_buy', models.FloatField()),
                ('number_stock', models.IntegerField()),
                ('serial', models.CharField(max_length=100)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.Entry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='product',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
