# Generated by Django 2.0.1 on 2018-05-01 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0007_auto_20180430_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='number_entry',
            new_name='code_fact',
        ),
    ]
